views/auth.py
"""Module to handle login/logout/register functions."""

from flask import Blueprint, request, url_for, redirect, render_template, flash
from flask.ext.login import (login_user, logout_user, login_required,
                             current_user)
from flask import session

from app import db
from models import User
from forms import LoginForm, RegistrationForm


login_Bp = Blueprint('login_page', __name__, template_folder='templates')
logout_Bp = Blueprint('logout_page', __name__, template_folder='templates')
register_Bp = Blueprint('register_page', __name__, template_folder='templates')


@login_Bp.route('/login', methods=['GET', 'POST'])
def login():
    """Login to application."""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.is_password_correct(form.password.data):
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            login_user(user, remember=form.remember_me.data)
            print(session.items())
            flash('Login was successful!')
            return redirect(url_for('home'))
        else:
            flash('Wrong credentials!')
    return render_template('login.html', form=form)


@logout_Bp.route('/logout')
@login_required
def logout():
    """Logout the current user."""
    current_user.authenticated = False
    db.session.commit()
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('home'))


@register_Bp.route('/register', methods=['GET', 'POST'])
def register():
    """Register a new user."""
    form = RegistrationForm()
    if form.validate_on_submit():
        username_exists = db.session.query(User).filter_by(
            username=form.username.data).first()
        email_exists = db.session.query(User).filter_by(
            email=form.email.data).first()
        if username_exists and email_exists:
            flash('Username and email are already taken!')
        elif username_exists:
            flash('Username is already taken!')
        elif email_exists:
            flash('Email is already taken!')
        else:
            user = User(username=form.username.data, email=form.email.data,
                        password=form.password.data)
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for('home'))
    return render_template('register.html', form=form)

templates/add_bookmark.html
{% from "_formhelpers.html" import render_field %}
{% extends 'index.html' %}


{% block title %}
    <title>Add new Bookmark</title>
{% endblock title %}


{% block content %}
    <form action="/add"  method="POST">
        <dl>
            {{ form.csrf_token }}
            {{ render_field(form.category) }}
            {{ render_field(form.title) }}
            {{ render_field(form.url) }}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class=flashes>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <p><input type="submit" value="Add">
        </dl>
    </form>
{% endblock content %}

templates/base.html
{% extends 'index.html' %}

{% block title %}
    <title>Python Resources</title>
{% endblock title %}


{% block content %}
    <strong>{{title}}</strong>
    <ul>
        {% for bookmark in results %}
        <li><a href={{bookmark.url}} target='_blank'>{{bookmark.title}}</a></li><br>
        {% endfor %}
    </ul>
{% endblock content %}

templates/index.html
<html>
    <head>
        {% block title %}
            <title>Python Resources</title>
        {% endblock title %}
    </head>

    <body>
        <ul>
            <li style="display:inline; padding: 8px;"><a href="{{ url_for('home') }}">Home</a></li>
            <li style="display:inline; padding: 8px;">|</li>

            {% if current_user.is_authenticated() %}
                <li style="display:inline; padding: 8px;">Welcome {{current_user.username}}</li>
                <li style="display:inline; padding: 8px;">|</li>
                <li style="display:inline; padding: 8px;"><a href="{{
                    url_for('get_my_categories') }}">My bookmarks</a></li>
                <li style="display:inline; padding: 8px;">|</li>
                <li style="display:inline; padding: 8px;"><a href="{{ url_for('add_bookmark') }}">Add bookmark</a></li>
                <li style="display:inline; padding: 8px;">|</li>
                <li style="display:inline; padding: 8px;"><a href="{{ url_for('update_bookmark') }}">Update bookmark</a></li>
                <li style="display:inline; padding: 8px;">|</li>
                <li style="display:inline; padding: 8px;"><a href="{{ url_for('logout_page.logout') }}">Log out</a></li>
            {% else %}
                <li style="display:inline; padding: 8px;"><a href="{{ url_for('login_page.login') }}">Log in</a></li>
                <li style="display:inline; padding: 8px;">|</li>
                <li style="display:inline; padding: 8px;"><a href="{{ url_for('register_page.register') }}">Register</a></li>
            {% endif %}
        <ul>
        <br>

        {% block content %}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class=flashes>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <br>
            <div style="clear:both">
                <strong>Categories</strong>
                <ul>
                    {% for relative_url, category in categories %}
                    <li><a href={{relative_url}}>{{category}}</a></li><br>
                    {% endfor %}
                </ul>
            </div>
        {% endblock content %}
    </body>
</html>